### PR TITLE
Update to SBT 1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rintcius** [comment]
@swiesner-dlr nice! 

Did you see this warning in the log?

```
/home/travis/build/rklaehn/radixtree/build.sbt:79: warning: lazy value CrossType in object AutoImport is deprecated (since 0.6.23): The built-in cross-project feature of sbt-scalajs is deprecated. Use the separate sbt plugin sbt-crossproject instead: https://github.com/portable-scala/sbt-crossproject
lazy val core = crossProject.crossType(CrossType.Pure).in(file("."))
                                       ^
```

**Comment by swiesner-dlr** [comment]
@rintcius I saw it, but I do not know how to fix it, and didn't have the time to fix it :)

**Comment by rintcius** [comment]
@swiesner-dlr ok, thanks! We can address that separately.

**Comment by ghost** [comment]
@rintcius Thanks for merging :)

**Pull request merged**
