### PR TITLE
Add getOrNull

### PR DESCRIPTION
**Pull request by japgolly**
This is more efficient than `get` or `contains` then `apply`.

### CODE REVIEW

**Comment by rklaehn** [comment]
Have you done a benchmark to confirm that this is really faster? In my experience, very short-lived objects such as an option that is created and then immediately thrown away are often optimized away by the java8 JIT compiler.

Would something like `getOrDefault(key: K, default: V): V` also work for you?

But in any case, if you add a test to get the coverage back to 100%, I will merge it.

**Comment by japgolly** [comment]
Hi. No I haven't done a benchmark. That would be really awesome if Java8 JIT'd them away. Separately though, if I have a `getOrNull` method I can know for sure that on any platform it won't be boxed so if it's still ok with you, I'll keep the method add a test to keep the coverage up.

`getOrDefault(key: K, default: V): V` would also be a nice method to have. Should I add that too?

**Comment by japgolly** [comment]
Hi @rklaehn, I've updated the PR. Cheers.

**Comment by rklaehn** [comment]
Thanks. Sorry about not noticing this. I have been really busy with a project.

**Pull request merged**
